### ISSUE TITLE
Error: OSError: mysql_config not found

### ISSUE THREAD

**Issue by fclesio** [WZBSocialScienceCenter/germalemma#4]
When I try to install using the `$ pip3 install -U germalemma` command, I get this error:

```
Collecting germalemma
  Using cached https://files.pythonhosted.org/packages/ff/f9/9fb28336e480b0e3744a8633813f9e1bc3f49a4eb3d7f6ad23e923a5a5b4/germalemma-0.1.1-py3-none-any.whl
Requirement already satisfied, skipping upgrade: Pyphen>=0.9.5 in /usr/local/lib/python3.7/site-packages (from germalemma) (0.9.5)
Collecting Pattern>=3.6 (from germalemma)
  Using cached https://files.pythonhosted.org/packages/1e/07/b0e61b6c818ed4b6145fe01d1c341223aa6cfbc3928538ad1f2b890924a3/Pattern-3.6.0.tar.gz
Collecting future (from Pattern>=3.6->germalemma)
  Using cached https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz
Collecting backports.csv (from Pattern>=3.6->germalemma)
  Using cached https://files.pythonhosted.org/packages/71/f7/5db9136de67021a6dce4eefbe50d46aa043e59ebb11c83d4ecfeb47b686e/backports.csv-1.0.6-py2.py3-none-any.whl
Collecting mysqlclient (from Pattern>=3.6->germalemma)
  Using cached https://files.pythonhosted.org/packages/f4/f1/3bb6f64ca7a429729413e6556b7ba5976df06019a5245a43d36032f1061e/mysqlclient-1.4.2.post1.tar.gz
    Complete output from command python setup.py egg_info:
    /bin/sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_b/h6xt6cb97hx66z_101nmhmqc0000gp/T/pip-install-qgfzyd98/mysqlclient/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/private/var/folders/_b/h6xt6cb97hx66z_101nmhmqc0000gp/T/pip-install-qgfzyd98/mysqlclient/setup_posix.py", line 51, in get_config
        libs = mysql_config("libs")
      File "/private/var/folders/_b/h6xt6cb97hx66z_101nmhmqc0000gp/T/pip-install-qgfzyd98/mysqlclient/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    OSError: mysql_config not found

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/_b/h6xt6cb97hx66z_101nmhmqc0000gp/T/pip-install-qgfzyd98/mysqlclient/
```

**Version**: '0.1.1'
**Python**:  3.7

Solution: Only to install install MySQL using `brew` or `pip`

`$ brew install mysql`

`$ pip3 install mysql`

I'll open a PR for this.

**Comment by fclesio** [comment]
The solution for Linux environment:

```
sudo apt-get install mysql-server &&
sudo apt-get install libmysqlclient-dev
```

**Comment by internaut** [comment]
Yes, and btw this is not related to germalemma but the "Pattern" package, which, for some reasons, requires MySQL.
I also think that you don't need to install the full mysql server, `sudo apt-get install libmysqlclient-dev` should be enough.
